name: "Label Issues"
on:
  issues:
    types: [opened, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "title"
          parameters: '[ { "keywords": ["functionality"], "labels": ["functionality"], "assignees": [] }, { "keywords": ["fun"], "labels": ["fun"], "assignees": [] }, { "keywords": ["patch"], "labels": ["patch"], "assignees": [] }, { "keywords": ["ricing"], "labels": ["ricing"], "assignees": [] } ]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
